FROM node:20
EXPOSE 8080
WORKDIR /opt/roboshop-cart
COPY *.js .
COPY package.json .
RUN npm install
ENV REDIS_HOST="redis" \
    CATALOGUE_HOST="catalogue" \
    CATALOGUE_PORT="8080"
CMD ["node","server.js"]